version: '3'
services:
  pdfactory:
    build: .
    command: "npm run dev"
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    environment:
      NODE_ENV: "development"
      VIRTUAL_HOST: "ppt.abbi-studio.local"
volumes: 
  node_modules: